#!/bin/bash

# Script pour aider au démarrage rapide du portfolio

echo "🎉 Bienvenue dans votre Portfolio Yass!"
echo ""
echo "📁 Vous avez reçu :"
echo "   ✅ Un portfolio complet en React 19 + TypeScript"
echo "   ✅ Support Français/Anglais intégré"
echo "   ✅ Mode Dark/Light"
echo "   ✅ Design moderne et responsive"
echo ""
echo "📚 Documentation incluse :"
echo "   📖 START_HERE.md ........................ 👈 COMMENCEZ PAR CELUI-CI"
echo "   📖 GETTING_STARTED.md .................. Guide de personnalisation"
echo "   📖 DEPLOYMENT.md ........................ Guide de déploiement"
echo "   📖 ADVANCED.md .......................... Cas d'usage avancés"
echo "   📖 GUIDE.md ............................. Documentation technique"
echo ""
echo "🚀 Commandes essentielles :"
echo "   npm run dev ............................ Démarrer le serveur local"
echo "   npm run build .......................... Build pour production"
echo "   npm run preview ........................ Prévisualiser le build"
echo ""
echo "📋 Prochaines étapes :"
echo "   1️⃣  Ouvrez START_HERE.md pour l'orientation"
echo "   2️⃣  Lisez GETTING_STARTED.md pour la personnalisation"
echo "   3️⃣  Modifiez vos contenus (texte, projets, infos)"
echo "   4️⃣  Testez avec npm run dev"
echo "   5️⃣  Lisez DEPLOYMENT.md pour mettre en ligne"
echo ""
echo "💻 Le site est actuellement en cours d'exécution sur :"
echo "   🌐 http://localhost:5173/"
echo ""
echo "✨ Bon amusement ! Créez un super portfolio ! 🚀"
